# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=100)),
                ('album_art', models.CharField(default='http://vignette4.wikia.nocookie.net/rip-lyl/images/1/13/-%3D.jpg/revision/latest?cb=20130313201437', max_length=5000)),
                ('genre', models.CharField(max_length=50)),
                ('album_rating', models.FloatField(default=0)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('artist_art', models.CharField(default='https://cdn.meme.am/cache/instances/folder787/500x/54965787.jpg', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listen_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listen_count', models.IntegerField(default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=250)),
                ('song_rating', models.FloatField(default=0)),
                ('song_file', models.CharField(default='C:\\Users\\', max_length=1000)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='api.Album')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRatedSongs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('song_rated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.AddField(
            model_name='listen_record',
            name='songid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Song'),
        ),
        migrations.AddField(
            model_name='listen_record',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.AddField(
            model_name='artist',
            name='label_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_artist', to='api.Label'),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(default='def', on_delete=django.db.models.deletion.CASCADE, related_name='rel_albums', to='api.Artist'),
        ),
    ]
