# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='label_name',
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(default='def', on_delete=django.db.models.deletion.CASCADE, related_name='rel_albums', to='music.ArtistRegistered'),
        ),
        migrations.AlterField(
            model_name='listen_record',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.UserRegistered'),
        ),
        migrations.AlterField(
            model_name='userratedsongs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.UserRegistered'),
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
