# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=32),
        ),
    ]
