# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20161127_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=100)),
                ('album_art', models.CharField(default='http://vignette4.wikia.nocookie.net/rip-lyl/images/1/13/-%3D.jpg/revision/latest?cb=20130313201437', max_length=500)),
                ('genre', models.CharField(max_length=50)),
                ('album_rating', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('artist', models.ForeignKey(default='def', on_delete=django.db.models.deletion.CASCADE, related_name='rel_albums', to='api.Artist')),
            ],
        ),
    ]
