# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20161127_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='label_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_artist', to='api.Label'),
        ),
    ]
