# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20161127_0227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='name',
            new_name='artist_name',
        ),
        migrations.AlterField(
            model_name='artist',
            name='label_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Label'),
        ),
    ]
