# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(default='Independent', max_length=500, unique=True),
        ),
    ]
