# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20161208_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistregistered',
            old_name='profilepicture',
            new_name='picture',
        ),
    ]
