# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20161208_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistregistered',
            name='picture',
        ),
    ]
