# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_remove_artistregistered_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistregistered',
            name='profilepicture',
            field=models.CharField(default='hello', max_length=200),
        ),
    ]
