# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_artistregistered_profilepicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistregistered',
            name='profilepicture',
        ),
        migrations.AddField(
            model_name='artistregistered',
            name='picture',
            field=models.CharField(default='', max_length=200),
        ),
    ]
