# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_userregistered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistregistered',
            name='label',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='api.Label'),
        ),
    ]
